### ISSUE TITLE
feature: have a timer default setting 

### ISSUE THREAD

**Issue by smtgpm** [SimonMarquis/SleepTimer#10]
Hi,
Would be cool if we could set the default time when opening the app, not on 0. That way when you open the app you just have to start the timer instead of also having to set the time
Thanks

**Comment by SimonMarquis** [comment]
Hi, thanks for the idea, but to me, this goes against the simplicity of the app.
It would require to create a specific UI & interactions to support this kind of setting.
Hope this makes sense.

**Comment by smtgpm** [comment]
> Hi, thanks for the idea, but to me, this goes against the simplicity of the app. It would require to create a specific UI & interactions to support this kind of setting. Hope this makes sense.

Ah sorry my bad, guess I didn't look enough through the concept. No worries, thanks for the quick response
