### ISSUE TITLE
Add option to disable bluetooth

### ISSUE THREAD

**Issue by tysino** [SimonMarquis/SleepTimer#12]
Together with pausing music playback, also disabling bluetooth would be great. When the alarm in the morning hits through my bluetooth speaker it's quite an unpleasant start of the day.

Unfortunately my phone has no setting for where the alarm should be played. I have found no explicit "bluetooth sleep timer" app. Maybe I'll look into controlling bluetooth from termux.

Anyway, thanks for the app, the implemented features work great on my Android 11 phone.

**Comment by SimonMarquis** [comment]
Hi @tysino, thanks for the feedback, unfortunately this would require too much work and would go against the purpose of this project which aims to be minimalistic and to not provide any piece of user interface. Everything is controled by Android's System UI.
But you are welcome to fork this project if you want to.

**Comment by filipesmedeiros** [comment]
Hey @SimonMarquis, I was trying to make this work, but it's a hassle for me (whereas you already know what you're doing and have the setup, etc). Do you think I could commission this change to you? We can figure out the details if you are up for it! :)

**Comment by SimonMarquis** [comment]
Hi @filipesmedeiros, unfortunately I wont be able to work on this. And as I said earlier, this would require some amount of work and would go against the "simplicity" of this app. For example, we can't simply "disable" bluetooth, otherwise it would stop any other bluetooth device connected, and that will be counter productive. I hope this makes sense for you.

**Comment by filipesmedeiros** [comment]
Hey @SimonMarquis, thank you for the response! Just to clarify, I don't mind comissioning a fork. You wouldn't need to alter the current version in this repo. I am basically just asking for your help for coding a feature I would like to have on my fork, and paying you for it ahah

As a side note, I personally wouldn't mind turning off bluetooth completely, it would save energy by avoiding my speaker being on the whole night, and the phone having BT on all night as well. I suppose a lot of people would agree.

But I understand if you don't want to use time on this feature. And I thank you for the awesome simple app :)
