### ISSUE TITLE
Fdroid Repo not up to date

### ISSUE THREAD

**Issue by Kasi07** [SimonMarquis/SleepTimer#13]
I just noticed that the Fdroid Repo is out of date. The last version on there is v1.1.0.

**Comment by SimonMarquis** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12489

**Comment by SimonMarquis** [comment]
Version 1.2.0 is now available on [F-Droid](https://f-droid.org/en/packages/fr.smarquis.sleeptimer/).
