### ISSUE TITLE
not working on MIUI (grey tile)

### ISSUE THREAD

**Issue by igarca** [SimonMarquis/SleepTimer#14]
after some time installed (usually few day(s)), it stops working. it appears grey and when I tap, it does nothing.
I tried battery optimization, working on the background, clear cache, and it did not work. the only way to make it work again is reinstalling. it comes back to black.

![IMG_20230528_130626](https://github.com/SimonMarquis/SleepTimer/assets/85171692/b6acb6b9-4705-4649-88d6-29c7926d0c53)

thank you! it's an useful app.

**Comment by SimonMarquis** [comment]
This looks like MIUI is the culprit unfortunately...
- https://github.com/SimonMarquis/SleepTimer/issues/11
