### ISSUE TITLE
description in f-droid is confusing

### ISSUE THREAD

**Issue by cloo** [SimonMarquis/SleepTimer#2]
I was looking for a nap timer and by accident installed this app. It should be clear what it does from the description or even better, from the name.

**Comment by SimonMarquis** [comment]
Hi @cloo, do you have any suggestion that could improve the situation?
Renaming the app name might not be an option, but improving the description could easily be done.

**Comment by cloo** [comment]
I'd imagine something like that:
"Sleep timer helps you fall asleep while listening to your music or podcasts. When timer stops, playback of your audio app is automatically silenced and paused."

**Comment by SimonMarquis** [comment]
Thanks a lot for your suggestion. I'll update it as soon as I can. The Fdroid listing page should be automatically updated once it's done.

**Comment by SimonMarquis** [comment]
I hope this update will automatically be picked-up by F-Droid. If not, I'll try to find a way to force it.
