### ISSUE TITLE
A way to set default start time

### ISSUE THREAD

**Issue by MichelJonkman** [SimonMarquis/SleepTimer#31]
It would be awesome if we could set the default time and maybe even the increment time. This could simply be done through a config file somewhere on the filesystem so no UI has to be made for it.

**Comment by SimonMarquis** [comment]
Hi @MichelJonkman, unfortunately this would mean adding permissions to read the file system, handle reading files, exposing new APIs, documentation, etc. and this is not the goal of this project.
Furthermore, users that would create such configuration file and copy it to the appropriate location probably can simply re-compile this project with the values they want 😄

https://github.com/SimonMarquis/SleepTimer/blob/e88f7463cb6b4622ec44baa6dcb27f2bb9aa9ad4/app/src/main/java/fr/smarquis/sleeptimer/SleepNotification.kt#L26-L28

**Comment by MichelJonkman** [comment]
@SimonMarquis I'd love to recompile it myself but I have no knowledge of compiling Android apps, is this easy to do?

**Comment by MichelJonkman** [comment]
Thank you for the explanation, I will do this when I hopefully don't forget about it 😛
