### ISSUE TITLE
Ability to donate to author is missing

### ISSUE THREAD

**Issue by peterrus** [SimonMarquis/SleepTimer#6]
This is one of these apps that, despite being so simple, solve a really annoying problem for me.

If you @SimonMarquis have some way to accept donations I will include you in my next FOSS-donation run.

If not: please see this as a token of my appreciation.

**Comment by SimonMarquis** [comment]
Thanks a lot for those kind words!
I currently don't have any way of accepting donations though I might one day join the GitHub sponsor program.

**Comment by peterrus** [comment]
Sounds good! Feel free to close this issue, or keep it open as a sort of todo if you want.
