### ISSUE TITLE
1 minute increment for more precise timer

### ISSUE THREAD

**Issue by PrPierre** [SimonMarquis/SleepTimer#76]
Hello !

I think it would be nice if we could have the possibility to adjust timer with +1/-1 minute increments.

I see multiple use cases for this :
- To test if sleep timer app is functional with any app you want to use with --> instead of waiting at least 10 minutes, you can test in 1 minute
- To be able to have a more precise timer to set overall --> I often want to set timer for 15 or 25 minutes for example

With this addition, maybe the UI could go from this :
+10 | -10 | Cancel
To this :
+10 | +1 | -1 | -10 | Cancel

Is this something you could maybe add ?

Thanks !

**Comment by SimonMarquis** [comment]
Hi @PrPierre, thanks for your suggestions, but this is not something I'm going to add to this project, but you can fork it and build your own.
See also this PR:
- https://github.com/SimonMarquis/SleepTimer/pull/1

Thanks

**Comment by PrPierre** [comment]
I managed to build my own APK, it took me some time to realise I can only show up to 3 actions for a notification in its expanded form, so no "+10 | +1 | -1 | -10 | Cancel" format possible this way.

Intead I set "+5 | -5 | Cancel" with default timer set to 26min, in order to be able to resolve my listed use cases.

Thanks for the tip !
